MODULE ELEMENT_CLASS
USE BASE_CLASS
IMPLICIT NONE
!->+++++++++++++++++++++++++++++++++++++++++++++
TYPE,PUBLIC,EXTENDS(BASE) :: ELEMENT

    REAL(RDT),ALLOCATABLE :: RLGM(:,:),RLGC(:,:),RLGK(:,:),FC(:)

    REAL(RDT) :: FC1(3),MT1(3),FC2(3),MT2(3)

CONTAINS

    PROCEDURE,PUBLIC :: CONSTRUCT_ELEMENT
    PROCEDURE,PUBLIC :: MLEGGAUSS_ST
    PROCEDURE,PUBLIC :: MLEGGAUSS_FR
    PROCEDURE,PUBLIC :: DECONSTRUCT_ELEMENT
    PROCEDURE,PUBLIC :: rvclct
    PROCEDURE,PUBLIC :: rvclct2
    PROCEDURE,PUBLIC :: UMINT
    
    PROCEDURE,PRIVATE :: MX
    PROCEDURE,PRIVATE :: KFCFX
    PROCEDURE,PRIVATE :: KFIX
    PROCEDURE,PRIVATE :: KLX
    PROCEDURE,PRIVATE :: KNLX
    PROCEDURE,PRIVATE :: MCX
    PROCEDURE,PRIVATE :: FMINT
    PROCEDURE,PRIVATE :: RLCTRFB

END TYPE ELEMENT
!->+++++++++++++++++++++++++++++++++++++++++++++
CONTAINS 
!->+++++++++++++++++++++++++++++++++++++++++++++
!->+++++++++++++++++++++++++++++++++++++++++++++
!->+++++++++++++++PUBLIC++++++++++++++++++++++++++
!->+++++++++++++++++++++++++++++++++++++++++++++
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE CONSTRUCT_ELEMENT(THIS,ID,INPU)
USE INPUT_CLASS
IMPLICIT NONE
CLASS(ELEMENT) :: THIS
CLASS(INPUT) :: INPU
INTEGER,INTENT(IN) :: ID

    CALL THIS%CONSTRUCT_BASE(ID,INPU)

    ALLOCATE(THIS%RLGM(THIS%SMD,THIS%SMD),THIS%RLGC(THIS%SMD,THIS%SMD))
    ALLOCATE(THIS%RLGK(THIS%SMD,THIS%SMD),THIS%FC(THIS%SMD))

END SUBROUTINE
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE MLEGGAUSS_ST(THIS,R,EL1,BTAP,THP,THP1D,THP2D,OMG,SOL)
USE MBEAMAERO
implicit none
CLASS(ELEMENT) :: THIS
INTEGER,INTENT(IN)::SOL
REAL(RDT),INTENT(IN):: R
REAL(RDT),INTENT(IN)::EL1,BTAP,THP,THP1D,THP2D,OMG

REAL(RDT),EXTERNAL :: FWM

REAL(RDT) LL
REAL(RDT) RLGMT(THIS%SMD,THIS%SMD),RLGCT(THIS%SMD,THIS%SMD)
REAL(RDT) RLGK1T(THIS%SMD,THIS%SMD),RLGK2T(THIS%SMD,THIS%SMD)
REAL(RDT) RLGK3T(THIS%SMD,THIS%SMD),RLGK4T(THIS%SMD,THIS%SMD)
REAL(RDT) FC1T(THIS%SMD),FC2T(THIS%SMD)
REAL(RDT) HE,SS
REAL(RDT) PE(3),QE(3),RXUD,TER(3,3),PEG(3),QEG(3),PETIP(3)
REAL(RDT) SSA
INTEGER :: NBPLIA
integer i,J
INTEGER :: SMD  
REAL(RDT) LDLMT(THIS%SMD,THIS%SMD)

    LL=THIS%NOD(2)%RLUD*R-THIS%NOD(1)%RLUD*R
    
    RLGMT=0.0D0
    RLGCT=0.0D0
    RLGK1T=0.0D0
    RLGK2T=0.0D0
    RLGK3T=0.0D0
    RLGK4T=0.0D0
    FC1T=0.0D0
    FC2T=0.0D0
    
    THIS%RLGM=0.0D0
    THIS%RLGC=0.0D0
    THIS%RLGK=0.0D0
    THIS%FC=0.0D0
    
    THIS%CTFTMP1=0.0D0
    THIS%CTFTMP2=0.0D0 

    HE=THIS%NOD(1)%RLUD*R-EL1
    
      DO 10 I=NLG, 1, -1
        SS=(GT(I,NLG)+1.0)/2.0
                
        CALL THIS%GETLV(HE,SS,LL,BTAP,EL1,THP,THP1D,THP2D,OMG)

        CALL THIS%MX(RLGMT)
        CALL THIS%MCX(RLGCT)  
        CALL THIS%KLX(RLGK1T)
        CALL THIS%KNLX(RLGK2T,LL,I,NLG,GC,GT) 
        
        CALL THIS%KFCFX(RLGK3T,FC1T)  
        
        IF (THIS%GGT.NE.0.0) THEN
            CALL MAMU(TER,3,3,3,THIS%TEB,THIS%TBR)
            CALL MVMU2(PEG,3,3,TER,(/0.0D0,0.0d0,-THIS%MSLT*THIS%GGT/))
            CALL MVMU2(QEG,3,3,TER,(/0.0D0,0.0d0,0.0d0/)) 
        ELSE
            PEG=0.0
            QEG=0.0
        END IF     
        
        IF( (THIS%IS_AERO.EQ.1) .AND. (SOL .GE. 1)) THEN
            RXUD=THIS%NOD(1)%RLUD+THIS%XX/R
            CALL rxlct2(NBPLIA, SSA, NPTS, RXUD, RLUDAUD) 
            DO J=1,3
                PE(J)=FWM(FLCST_ST(J,NBPLIA),FLCST_ST(J,NBPLIA+1),SSA)
                QE(J)=FWM(MLCST_ST(J,NBPLIA),MLCST_ST(J,NBPLIA+1),SSA)  
            END DO 
            PE=PE+PEG
            QE=QE+QEG
            CALL THIS%KFIX(RLGK4T,FC2T,PE,QE)
        END IF     

    THIS%RLGM=THIS%RLGM+RLGMT*GC(I,NLG) 
    THIS%RLGC=THIS%RLGC+RLGCT*GC(I,NLG) 
    THIS%RLGK=THIS%RLGK+(RLGK1T+RLGK2T+RLGK3T+RLGK4T)*GC(I,NLG)
    THIS%FC=THIS%FC+(FC1T+FC2T)*GC(I,NLG)
        
10  CONTINUE

    THIS%RLGM=THIS%RLGM*LL/2.0
    THIS%RLGC=THIS%RLGC*LL/2.0
    THIS%RLGK=THIS%RLGK*LL/2.0
    THIS%FC=THIS%FC*LL/2.0
    
    THIS%NOD(1)%CTFGRL=THIS%NOD(2)%CTFGRL+THIS%CTFTMP2
    THIS%CTFTMP1=0.0D0
    THIS%CTFTMP2=0.0D0 
    IF(THIS%IS_TIP.EQ.1) THEN

        SMD=THIS%SMD
        LDLMT=TRANSPOSE(THIS%LDLM)

        CALL MATMLYTP(RLGK1T, SMD, SMD, SMD, SMD, LDLMT, THIS%RLGM, THIS%LDLCM)
        CALL MATMLYTP(RLGK2T, SMD, SMD, SMD, SMD, LDLMT, THIS%RLGM, THIS%LDMM)
        CALL MATMLYTP(RLGK3T, SMD, SMD, SMD, SMD, LDLMT, THIS%RLGC, THIS%LDLCM)
        CALL MATMLYTP(RLGK4T, SMD, SMD, SMD, SMD, LDLMT, THIS%RLGK, THIS%LDLKM)
        FC1T=MATMUL(LDLMT,THIS%FC)
            
        THIS%RLGM=RLGK1T
        THIS%RLGC=RLGK2T+RLGK3T
        THIS%RLGK=RLGK4T
        THIS%FC=FC1T
        
    END IF
        
END SUBROUTINE
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE MLEGGAUSS_FR(THIS,R,EL1,BTAP,THP,THP1D,THP2D,OMG,SOL)
USE MBEAMAERO
implicit none
CLASS(ELEMENT) :: THIS
INTEGER,INTENT(IN)::SOL
REAL(RDT),INTENT(IN):: R
REAL(RDT),INTENT(IN)::EL1,BTAP,THP,THP1D,THP2D,OMG

REAL(RDT),EXTERNAL :: FWM

REAL(RDT) HE,LL,SS
REAL(RDT) FCT1(3),MTT1(3),FCT2(3),MTT2(3)
REAL(RDT) XRRFB(3)
REAL(RDT) MTP1(3), TMP1(3,3)
REAL(RDT) RDRT(3),RXUD
REAL(RDT) SSA
integer i,J,NBPLIP1,NBPLIA

    LL=(THIS%NOD(2)%RLUD-THIS%NOD(1)%RLUD)*R
    RDRT=0.0D0

    THIS%FC1=0.0D0
    THIS%MT1=0.0D0
    THIS%FC2=0.0D0
    THIS%MT2=0.0D0

    FCT1=0.0D0
    MTT1=0.0D0
    FCT2=0.0D0
    MTT2=0.0D0

    HE=THIS%NOD(1)%RLUD*R-EL1
    
      DO 10 I=NLG, 1, -1
        SS=(GT(I,NLG)+1.0)/2.0
                
        CALL THIS%GETLV(HE,SS,LL,BTAP,EL1,THP,THP1D,THP2D,OMG)

        CALL THIS%FMINT(FCT1,MTT1)
        CALL THIS%RLCTRFB(XRRFB,HE,EL1) 

        CALL VCP(MTP1,XRRFB-RDRT,FCT1)

        MTT1=MTT1+MTP1 

        IF( (THIS%IS_AERO.EQ.1) .AND. (SOL .GE. 1)) THEN
            RXUD=THIS%NOD(1)%RLUD+THIS%XX/R
            CALL rxlct2(NBPLIA, SSA, NPTS, RXUD, RLUDAUD) 
            DO J=1,3
                FCT2(J)=FWM(FLCST_FR(J,NBPLIA),FLCST_FR(J,NBPLIA+1),SSA)
                MTT2(J)=FWM(MLCST_FR(J,NBPLIA),MLCST_FR(J,NBPLIA+1),SSA)  
            END DO 
             
            CALL VCP(MTP1,XRRFB-RDRT,FCT2) 
            MTT2=MTT2+MTP1 
        END IF     

            THIS%FC1=THIS%FC1+FCT1*GC(I,NLG)        
            THIS%MT1=THIS%MT1+MTT1*GC(I,NLG)

            THIS%FC2=THIS%FC2+FCT2*GC(I,NLG)        
            THIS%MT2=THIS%MT2+MTT2*GC(I,NLG)
        
10  CONTINUE

    THIS%FC1=THIS%FC1*LL/2.0
    THIS%MT1=THIS%MT1*LL/2.0
    
    THIS%FC2=THIS%FC2*LL/2.0
    THIS%MT2=THIS%MT2*LL/2.0

    IF(THIS%IS_TIP.EQ.1) THEN

!        SMD=THIS%SMD
!        LDLMT=TRANSPOSE(THIS%LDLM)
!
!        CALL MATMLYTP(RLGK1T, SMD, SMD, SMD, SMD, LDLMT, THIS%RLGM, THIS%LDLCM)
!        CALL MATMLYTP(RLGK2T, SMD, SMD, SMD, SMD, LDLMT, THIS%RLGM, THIS%LDMM)
!        CALL MATMLYTP(RLGK3T, SMD, SMD, SMD, SMD, LDLMT, THIS%RLGC, THIS%LDLCM)
!        CALL MATMLYTP(RLGK4T, SMD, SMD, SMD, SMD, LDLMT, THIS%RLGK, THIS%LDLKM)
!        FC1T=MATMUL(LDLMT,THIS%FC)
!            
!        THIS%RLGM=RLGK1T
!        THIS%RLGC=RLGK2T+RLGK3T
!        THIS%RLGK=RLGK4T
!        THIS%FC=FC1T

    END IF
        
END SUBROUTINE
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE DECONSTRUCT_ELEMENT(THIS)
USE INPUT_CLASS
IMPLICIT NONE
CLASS(ELEMENT) :: THIS

    CALL THIS%DECONSTRUCT_BASE()

    DEALLOCATE(THIS%RLGM,THIS%RLGC)
    DEALLOCATE(THIS%RLGK,THIS%FC)

END SUBROUTINE
!->+++++++++++++++++++++++++++++++++++++++++++++
!->+++++++++++++++++++++++++++++++++++++++++++++
!->+++++++++++++++PRIVATE+++++++++++++++++++++++++
!->+++++++++++++++++++++++++++++++++++++++++++++
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE MX(THIS,RLGT)
IMPLICIT NONE
CLASS(ELEMENT) :: THIS
REAL(RDT),INTENT(OUT)::RLGT(THIS%SMD,THIS%SMD)

INTEGER ::SMD,NAD,NBD
INTEGER :: I,J
    SMD=THIS%SMD
    NAD=THIS%NAD
    NBD=THIS%NBD
    !->++++++++++++++
    RLGT=0.0D0
    I=1
    J=1
    RLGT(I:I+NAD-1,J:J+NAD-1)=THIS%MSLT*THIS%FCFC(:,:)
    
    J=J+NAD

    J=J+NAD
    RLGT(I:I+NAD-1,J:J+NBD-1)=-THIS%MZMB*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    RLGT(I:I+NAD-1,J:J+NBD-1)=-THIS%MEMB*THIS%FCPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    RLGT(I:I+NAD-1,J:J+NBD-1)=-THIS%MD1B*THIS%FCPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    RLGT(I:I+NAD-1,J:J+NBD-1)=-THIS%IMZZB*THIS%FCPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    RLGT(I:I+NAD-1,J:J+NBD-1)=-THIS%IMEZB*THIS%FCPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))

    !->++++++++++++++

    I=I+NAD
    J=I
    RLGT(I:I+NAD-1,J:J+NAD-1)=THIS%MSLT*THIS%FCFC(:,:)
    
    J=J+NAD
    RLGT(I:I+NAD-1,J:J+NBD-1)=THIS%MEMB*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    RLGT(I:I+NAD-1,J:J+NBD-1)=-THIS%MZMB*THIS%FCPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    RLGT(I:I+NAD-1,J:J+NBD-1)=-THIS%MD2B*THIS%FCPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    RLGT(I:I+NAD-1,J:J+NBD-1)=-THIS%IMZEB*THIS%FCPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    RLGT(I:I+NAD-1,J:J+NBD-1)=-THIS%IMEEB*THIS%FCPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))

    !->++++++++++++++

    I=I+NAD
    J=I
    RLGT(I:I+NBD-1,J:J+NBD-1)=(THIS%IMEET+THIS%IMZZT)*THIS%FQFQ(:,:)

    !->++++++++++++++

    I=I+NBD
    J=I
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%MSLT*THIS%FQFQ(:,:)
    
    J=J+NBD
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%MD0T*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%MEMT*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%MZMT*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

    !->++++++++++++++

    I=I+NBD
    J=I
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%MD3T*THIS%FQFQ(:,:)
    
    J=J+NBD
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%MD1T*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%MD2T*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

    !->++++++++++++++

    I=I+NBD
    J=I
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%IMZZT*THIS%FQFQ(:,:)
    
    J=J+NBD
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%IMEZT*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

    !->++++++++++++++

    I=I+NBD
    J=I
    RLGT(I:I+NBD-1,J:J+NBD-1)=THIS%IMEET*THIS%FQFQ(:,:)


END SUBROUTINE
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE MCX(THIS,RLGT)           
IMPLICIT NONE
CLASS(ELEMENT) :: THIS
REAL(RDT),INTENT(OUT)::RLGT(THIS%SMD,THIS%SMD)

REAL(RDT) M11CC,M12CC1,M12CC2,M12CC3,M13CC,M14CC,M15CC,M16CC,M17CC
REAL(RDT) M22CC,M23CC,M24CC,M25CC,M26CC,M27CC
REAL(RDT) M34CC,M35CC,M36CC,M37CC

INTEGER I,J
INTEGER :: SMD,NAD,NBD
    !->++++++++++++++
    SMD=THIS%SMD
    NAD=THIS%NAD
    NBD=THIS%NBD
    
    RLGT=0.0D0
    I=1
    J=1
    M11CC=2.0*THIS%OMGE(3)*THIS%MEMB
    RLGT(I:I+NAD-1,J:J+NAD-1)=M11CC*(THIS%FCPFC(:,:)-TRANSPOSE(THIS%FCPFC(:,:)))
    
    J=J+NAD
    M12CC1=THIS%OMGE(1)*THIS%MSLT
    M12CC2=THIS%OMGE(2)*THIS%MEMB
    M12CC3=THIS%OMGE(3)*THIS%MZMB
    RLGT(I:I+NAD-1,J:J+NAD-1)=-2.0*(M12CC1*THIS%FCFC(:,:)+M12CC2*THIS%FCPFC(:,:)+M12CC3*TRANSPOSE(THIS%FCPFC(:,:)))
    RLGT(J:J+NAD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NAD-1))
    
    J=J+NAD
    M13CC=-2.0*THIS%OMGE(1)*THIS%MEMB
    RLGT(I:I+NAD-1,J:J+NBD-1)=M13CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    M14CC=2.0*THIS%OMGE(3)*THIS%MSLT
    RLGT(I:I+NAD-1,J:J+NBD-1)=M14CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    M15CC=2.0*THIS%OMGE(3)*THIS%MD0T
    RLGT(I:I+NAD-1,J:J+NBD-1)=M15CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    M16CC=2.0*THIS%OMGE(3)*THIS%MEMT
    RLGT(I:I+NAD-1,J:J+NBD-1)=M16CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    M17CC=2.0*THIS%OMGE(3)*THIS%MZMT
    RLGT(I:I+NAD-1,J:J+NBD-1)=M17CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      

    !---------------

    I=I+NAD
    J=I
    M22CC=-2.0*THIS%OMGE(2)*THIS%MZMB
    RLGT(I:I+NAD-1,J:J+NAD-1)=M22CC*(THIS%FCPFC(:,:)-TRANSPOSE(THIS%FCPFC(:,:)))
    
    J=J+NAD
    M23CC=-2.0*THIS%OMGE(1)*THIS%MZMB
    RLGT(I:I+NAD-1,J:J+NBD-1)=M23CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    M24CC=-2.0*THIS%OMGE(2)*THIS%MSLT
    RLGT(I:I+NAD-1,J:J+NBD-1)=M24CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    M25CC=-2.0*THIS%OMGE(2)*THIS%MD0T
    RLGT(I:I+NAD-1,J:J+NBD-1)=M25CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
      
    J=J+NBD
    M26CC=-2.0*THIS%OMGE(2)*THIS%MEMT
    RLGT(I:I+NAD-1,J:J+NBD-1)=M26CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    M27CC=-2.0*THIS%OMGE(2)*THIS%MZMT
    RLGT(I:I+NAD-1,J:J+NBD-1)=M27CC*THIS%FCFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=-TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))

    !---------------

    I=I+NAD
    J=I

    J=J+NBD
    M34CC=-2.0*(THIS%OMGE(2)*THIS%MEMB+THIS%OMGE(3)*THIS%MZMB)
    RLGT(I:I+NBD-1,J:J+NBD-1)=M34CC*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=-TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
      
    J=J+NBD

    M35CC=-2.0*(THIS%OMGE(2)*THIS%MD1B+THIS%OMGE(3)*THIS%MD2B)
    RLGT(I:I+NBD-1,J:J+NBD-1)=M35CC*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=-TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    M36CC=-2.0*(THIS%OMGE(2)*THIS%IMZZB+THIS%OMGE(3)*THIS%IMZEB)
    RLGT(I:I+NBD-1,J:J+NBD-1)=M36CC*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=-TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
      
    J=J+NBD
    M37CC=-2.0*(THIS%OMGE(2)*THIS%IMEZB+THIS%OMGE(3)*THIS%IMEEB)
    RLGT(I:I+NBD-1,J:J+NBD-1)=M37CC*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=-TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

END SUBROUTINE
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE KLX(THIS,RLGT)
IMPLICIT NONE
CLASS(ELEMENT) :: THIS
REAL(RDT),INTENT(OUT)::RLGT(THIS%SMD,THIS%SMD)

REAL(RDT),EXTERNAL::FABSC  

INTEGER ::SMD,NAD,NBD
INTEGER :: I,J

    REAL(RDT) K11LC,K12LC,K13LC,K14LC,K15LC1,K15LC2,K16LC1,K16LC2,K17LC1,K17LC2
    REAL(RDT) K22LC,K23LC,K24LC,K25LC1,K25LC2,K26LC1,K26LC2,K27LC1,K27LC2
    REAL(RDT) K33LC,K34LC,K35LC1,K35LC2,K36LC1,K36LC2,K37LC1,K37LC2
    REAL(RDT) K44LC,K45LC1,K45LC2,K46LC1,K46LC2,K47LC1,K47LC2
    REAL(RDT) K55LC1,K55LC2,K55LC3,K56LC1,K56LC2,K56LC3,K56LC4,K57LC1,K57LC2,K57LC3,K57LC4
    REAL(RDT) K66LC1,K66LC2,K66LC3,K67LC1,K67LC2,K67LC3,K67LC4
    REAL(RDT) K77LC1,K77LC2,K77LC3

    !->++++++++++++++
    SMD=THIS%SMD
    NAD=THIS%NAD
    NBD=THIS%NBD

    RLGT=0.0D0
    I=1
    J=1
    K11LC=FABSC(THIS%EIZZB,-THIS%EIEZB,THIS%BTAT)
    RLGT(I:I+NAD-1,J:J+NAD-1)=K11LC*THIS%FCPPFCPP(:,:)
    
    J=J+NAD
    K12LC=FABSC(THIS%EIZEB,-THIS%EIEEB,THIS%BTAT)
    RLGT(I:I+NAD-1,J:J+NAD-1)=K12LC*THIS%FCPPFCPP(:,:)
    RLGT(J:J+NAD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NAD-1))
    
    J=J+NAD
    K13LC=-THIS%EAB1B
    RLGT(I:I+NAD-1,J:J+NBD-1)=K13LC*THIS%FCPPFQP(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    K14LC=-THIS%EAEAB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K14LC*THIS%FCPPFQP(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    K15LC1=-THIS%EAD1B
    K15LC2=-(THIS%TA0T*THIS%EAD1PB+THIS%EAB6B)
    RLGT(I:I+NAD-1,J:J+NBD-1)=K15LC1*THIS%FCPPFQP(:,:)+K15LC2*THIS%FCPPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    K16LC1=-THIS%EIZZB
    K16LC2=-(THIS%GEAEBB+THIS%TA0T*THIS%EIEZB)
    RLGT(I:I+NAD-1,J:J+NBD-1)=K16LC1*THIS%FCPPFQP(:,:)+K16LC2*THIS%FCPPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    K17LC1=-THIS%EIEZB
    K17LC2=-(THIS%GZAECB-THIS%TA0T*THIS%EIZZB)
    RLGT(I:I+NAD-1,J:J+NBD-1)=K17LC1*THIS%FCPPFQP(:,:)+K17LC2*THIS%FCPPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))

    !->++++++++++++++

    I=I+NAD
    J=I
    K22LC=FABSC(THIS%EIEEB,THIS%EIZEB,THIS%BTAT)
    RLGT(I:I+NAD-1,J:J+NAD-1)=K22LC*THIS%FCPPFCPP(:,:)
    
    J=J+NAD
    K23LC=-THIS%EAB2B
    RLGT(I:I+NAD-1,J:J+NBD-1)=K23LC*THIS%FCPPFQP(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    K24LC=-THIS%EAZAB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K24LC*THIS%FCPPFQP(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    K25LC1=-THIS%EAD2B
    K25LC2=-(THIS%TA0T*THIS%EAD2PB+THIS%EAB7B)
    RLGT(I:I+NAD-1,J:J+NBD-1)=K25LC1*THIS%FCPPFQP(:,:)+K25LC2*THIS%FCPPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    K26LC1=-THIS%EIZEB
    K26LC2=-(THIS%GEAZBB+THIS%TA0T*THIS%EIEEB)
    RLGT(I:I+NAD-1,J:J+NBD-1)=K26LC1*THIS%FCPPFQP(:,:)+K26LC2*THIS%FCPPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))
    
    J=J+NBD
    K27LC1=-THIS%EIEEB
    K27LC2=-(THIS%GZAZCB-THIS%TA0T*THIS%EIZEB)
    RLGT(I:I+NAD-1,J:J+NBD-1)=K27LC1*THIS%FCPPFQP(:,:)+K27LC2*THIS%FCPPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NAD-1)=TRANSPOSE(RLGT(I:I+NAD-1,J:J+NBD-1))

    !->++++++++++++++
    
    I=I+NAD
    J=I
    K33LC=THIS%GJT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K33LC*THIS%FQPFQP(:,:)
    
    J=J+NBD
    K34LC=THIS%EAB0T
    RLGT(I:I+NBD-1,J:J+NBD-1)=K34LC*THIS%FQPFQP(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    K35LC1=THIS%EAB3T
    K35LC2=THIS%TA0T*THIS%EAB3PT+THIS%EAB14T
    RLGT(I:I+NBD-1,J:J+NBD-1)=K35LC1*THIS%FQPFQP(:,:)+K35LC2*THIS%FQPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    K36LC1=THIS%EAB1T
    K36LC2=THIS%EAB12T+THIS%TA0T*THIS%EAB2T
    RLGT(I:I+NBD-1,J:J+NBD-1)=K36LC1*THIS%FQPFQP(:,:)+K36LC2*THIS%FQPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    K37LC1=THIS%EAB2T
    K37LC2=THIS%EAB10T-THIS%TA0T*THIS%EAB1T
    RLGT(I:I+NBD-1,J:J+NBD-1)=K37LC1*THIS%FQPFQP(:,:)+K37LC2*THIS%FQPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

    !->++++++++++++++

    I=I+NBD
    J=I
    K44LC=THIS%EAT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K44LC*THIS%FQPFQP(:,:)
    
    J=J+NBD
    K45LC1=THIS%EAD0T
    K45LC2=THIS%TA0T*THIS%EAD0PT+THIS%EAB5T
    RLGT(I:I+NBD-1,J:J+NBD-1)=K45LC1*THIS%FQPFQP(:,:)+K45LC2*THIS%FQPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    K46LC1=THIS%EAEAT
    K46LC2=THIS%GEAT+THIS%TA0T*THIS%EAZAT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K46LC1*THIS%FQPFQP(:,:)+K46LC2*THIS%FQPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    K47LC1=THIS%EAZAT
    K47LC2=THIS%GZAT-THIS%TA0T*THIS%EAEAT  
    RLGT(I:I+NBD-1,J:J+NBD-1)=K47LC1*THIS%FQPFQP(:,:)+K47LC2*THIS%FQPFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

    !->++++++++++++++
    
    I=I+NBD
    J=I
    K55LC1=THIS%EAD3T
    K55LC2=THIS%EAB8T+THIS%TA0T*THIS%EAD5T
    K55LC3=THIS%EAB15T+2*THIS%TA0T*THIS%EAB8PT+THIS%TA0T**2*THIS%EAD3PT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K55LC1*THIS%FQPFQP(:,:)+K55LC2*(THIS%FQPFQ(:,:)+TRANSPOSE(THIS%FQPFQ(:,:)))+K55LC3*THIS%FQFQ(:,:)
    
    J=J+NBD
    K56LC1=THIS%EAD1T
    K56LC2=THIS%EAD7T+THIS%TA0T*THIS%EAD2T
    K56LC3=THIS%EAB6T+THIS%TA0T*THIS%EAD1PT
    K56LC4=THIS%EAB13T+THIS%TA0T*THIS%EAD7PT+THIS%TA0T*THIS%EAB7T+THIS%TA0T**2*THIS%EAD2PT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K56LC1*THIS%FQPFQP(:,:)+K56LC2*THIS%FQPFQ(:,:)+K56LC3*TRANSPOSE(THIS%FQPFQ(:,:))+K56LC4*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    J=J+NBD
    K57LC1=THIS%EAD2T
    K57LC2=THIS%EAD6T-THIS%TA0T*THIS%EAD1T
    K57LC3=THIS%EAB7T+THIS%TA0T*THIS%EAD2PT
    K57LC4=THIS%EAB11T+THIS%TA0T*THIS%EAD6PT-THIS%TA0T*THIS%EAB6T-THIS%TA0T**2*THIS%EAD1PT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K57LC1*THIS%FQPFQP(:,:)+K57LC2*THIS%FQPFQ(:,:)+K57LC3*TRANSPOSE(THIS%FQPFQ(:,:))+K57LC4*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

    !->++++++++++++++
    
    I=I+NBD
    J=I
    K66LC1=THIS%EIZZT
    K66LC2=THIS%GEAEBT+THIS%TA0T*THIS%EIEZT
    K66LC3=THIS%GEEAT+2*THIS%TA0T*THIS%GEAZBT+THIS%TA0T**2*THIS%EIEET
    RLGT(I:I+NBD-1,J:J+NBD-1)=K66LC1*THIS%FQPFQP(:,:)+K66LC2*(THIS%FQPFQ(:,:)+TRANSPOSE(THIS%FQPFQ(:,:)))+K66LC3*THIS%FQFQ(:,:)
    
    J=J+NBD
    K67LC1=THIS%EIEZT
    K67LC2=THIS%GZAECT-THIS%TA0T*THIS%EIZZT
    K67LC3=THIS%GEAZBT+THIS%TA0T*THIS%EIEET
    K67LC4=THIS%GEZAT+THIS%TA0T*THIS%GZAZCT-THIS%TA0T*THIS%GEAEBT-THIS%TA0T**2*THIS%EIEZT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K67LC1*THIS%FQPFQP(:,:)+K67LC2*THIS%FQPFQ(:,:)+K67LC3*TRANSPOSE(THIS%FQPFQ(:,:))+K67LC4*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    
    !->++++++++++++++

    I=I+NBD
    J=I
    K77LC1=THIS%EIEET
    K77LC2=THIS%GZAZCT-THIS%TA0T*THIS%EIEZT
    K77LC3=THIS%GZZAT-2*THIS%TA0T*THIS%GZAECT+THIS%TA0T**2*THIS%EIZZT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K77LC1*THIS%FQPFQP(:,:)+K77LC2*(THIS%FQPFQ(:,:)+TRANSPOSE(THIS%FQPFQ(:,:)))+K77LC3*THIS%FQFQ(:,:)
    
END SUBROUTINE 
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE KNLX(THIS,RLGT,LL,IGC,NLG,GC,GT)  
IMPLICIT NONE
CLASS(ELEMENT) :: THIS

INTEGER,INTENT(IN):: IGC,NLG
REAL(RDT),INTENT(IN):: LL
REAL(RDT),INTENT(IN)::GC(NLG,NLG),GT(NLG,NLG)
REAL(RDT),INTENT(OUT)::RLGT(THIS%SMD,THIS%SMD)


REAL(RDT),EXTERNAL:: FABSC

INTEGER I,J

REAL(RDT) TX1,TX2,TX3,TX4,TX5,TX6,TX7,TX8,TX9,TX10,TX11,TX12 

REAL(RDT) PH0

REAL(RDT) ZUB
REAL(RDT) CTF, CTFT1, CTFT2, FL

REAL(RDT) VXB,SXBP,MYBP,MZBP,TXB

REAL(RDT) K11NLC1,K11NLC2,K11NLC3,K11NLC4,K12NLC1,K12NLC2,K12NLC3,K13NLC
REAL(RDT) K21NLC1,K21NLC2,K21NLC3,K22NLC1,K22NLC2,K22NLC3,K22NLC4,K23NLC
REAL(RDT) K31NLC1,K31NLC2,K31NLC3,K32NLC1,K32NLC2,K32NLC3,K33NLC
REAL(RDT) K41NLC1,K41NLC2,K42NLC1,K42NLC2,K43NLC
REAL(RDT) K51NLC1,K51NLC2,K51NLC3,K51NLC4,K52NLC1,K52NLC2,K52NLC3,K52NLC4,K53NLC1,K53NLC2
REAL(RDT) K61NLC1,K61NLC2,K61NLC3,K62NLC1,K62NLC2,K62NLC3,K63NLC
REAL(RDT) K71NLC1,K71NLC2,K71NLC3,K72NLC1,K72NLC2,K72NLC3,K73NLC
INTEGER :: SMD,NAD,NBD
    !->++++++++++++++
    SMD=THIS%SMD
    NAD=THIS%NAD
    NBD=THIS%NBD

    TX1=FABSC(-THIS%SW1X,THIS%SV1X,THIS%BTAT)
    TX2=FABSC(-THIS%EIZEB,THIS%EIEEB,THIS%BTAT)
    TX4=FABSC(THIS%EIZZB,-THIS%EIEZB,THIS%BTAT)
    TX6=FABSC(THIS%EIEEB,THIS%EIZEB,THIS%BTAT)
    TX9=FABSC(THIS%EIEZB,THIS%EIZZB,THIS%BTAT)
    TX11=FABSC(THIS%SV2X,THIS%SW2X,THIS%BTAT)

    PH0=-TX1*TX11

    !>++++++++++++++++++
    ZUB=THIS%MZMB*(-THIS%TV3(1)+THIS%SW1X2T-THIS%TV1(1)*THIS%SW1X-2.0*THIS%OMGE(3)*THIS%SPH1T+THIS%TV2(1)*THIS%SPH) &
            +THIS%MEMB*(-THIS%TV2(1)+THIS%SV1X2T-THIS%TV1(1)*THIS%SV1X-2.0*THIS%OMGE(2)*THIS%SPH1T-THIS%TV3(1)*THIS%SPH) &
            -THIS%MSLT*(-THIS%HOMGB(1)+THIS%SU2T-2.0*THIS%OMGE(3)*THIS%SV1T+2.0*THIS%OMGE(2)*THIS%SW1T&
            -THIS%TV1(1)*(THIS%XX+THIS%SU)+THIS%TV2(1)*THIS%SV+THIS%TV3(1)*THIS%SW) & 
            -THIS%MD0T*(THIS%SALP2T-THIS%TV1(1)*THIS%SALP)-THIS%MEMT*(THIS%SGE2T&
            -THIS%TV1(1)*THIS%SGE)-THIS%MZMT*(THIS%SGZ2T-THIS%TV1(1)*THIS%SGZ)

     
    IF(IGC .EQ. NLG) THEN               
        CTFT1=ZUB*(1.0-GT(IGC,NLG))*LL*0.5
    ELSE
        CTFT1=ZUB*(GT(IGC+1,NLG)-GT(IGC,NLG))*LL*0.5 
    END IF         
    THIS%CTFTMP1=THIS%CTFTMP1+CTFT1 

    CTFT2=ZUB*GC(IGC,NLG)*LL*0.5
    THIS%CTFTMP2=THIS%CTFTMP2+CTFT2  

    CTF=THIS%NOD(2)%CTFGRL+THIS%CTFTMP1

    !>++++++++++++++++++
    FL=0.5*THIS%EAC0T*THIS%SPH1X**2-THIS%SV2X*(THIS%EAEAB-THIS%SPH*THIS%EAZAB)-THIS%SW2X*(THIS%EAZAB+THIS%SPH*THIS%EAEAB)&
        +THIS%EAB0T*(THIS%SPH1X+PH0)+THIS%EAD0T*THIS%SALP1X+(THIS%TA0T*THIS%EAD0PT+THIS%EAB5T)*THIS%SALP&
        +THIS%EAEAT*THIS%SGE1X+THIS%EAZAT*THIS%SGZ1X+(THIS%GEAT+THIS%TA0T*THIS%EAZAT)*THIS%SGE+(THIS%GZAT-THIS%TA0T*THIS%EAEAT)*THIS%SGZ
            
    TX12=(CTF-FL)/THIS%EAT     
          
    VXB=THIS%EAT*TX12+FL
    
    SXBP=THIS%EAB0T*TX12-THIS%SV2X*THIS%EAB1B-THIS%SW2X*THIS%EAB2B&
            +THIS%GJT*THIS%SPH1X+THIS%EAB3T*THIS%SALP1X+(THIS%TA0T*THIS%EAB3PT+THIS%EAB14T)*THIS%SALP&
            +THIS%EAB1T*THIS%SGE1X+THIS%EAB2T*THIS%SGZ1X+(THIS%EAB12T+THIS%TA0T*THIS%EAB2T)*THIS%SGE+(THIS%EAB10T-THIS%TA0T*THIS%EAB1T)*THIS%SGZ

    MYBP=THIS%EAZAT*TX12-THIS%SV2X*THIS%EIEZB-THIS%SW2X*THIS%EIEEB&
            +THIS%EAB2T*THIS%SPH1X+THIS%EAD2T*THIS%SALP1X+(THIS%TA0T*THIS%EAD2PT+THIS%EAB7T)*THIS%SALP&
            +THIS%EIEZT*THIS%SGE1X+THIS%EIEET*THIS%SGZ1X+(THIS%GEAZBT+THIS%TA0T*THIS%EIEET)*THIS%SGE+(THIS%GZAZCT-THIS%TA0T*THIS%EIEZT)*THIS%SGZ

    MZBP=THIS%EAEAT*TX12-THIS%SV2X*THIS%EIZZB-THIS%SW2X*THIS%EIZEB&
            +THIS%EAB1T*THIS%SPH1X+THIS%EAD1T*THIS%SALP1X+(THIS%TA0T*THIS%EAD1PT+THIS%EAB6T)*THIS%SALP&
            +THIS%EIZZT*THIS%SGE1X+THIS%EIEZT*THIS%SGZ1X+(THIS%GEAEBT+THIS%TA0T*THIS%EIEZT)*THIS%SGE+(THIS%GZAECT-THIS%TA0T*THIS%EIZZT)*THIS%SGZ
    MZBP=-MZBP

    TXB=THIS%EAC0T*TX12+0.5*THIS%EAC3T*THIS%SPH1X**2-THIS%SV2X*(THIS%EAC1B-THIS%SPH*THIS%EAC2B)&
            -THIS%SW2X*(THIS%EAC2B+THIS%SPH*THIS%EAC1B)+THIS%EAB4T*THIS%SPH1X+THIS%EAD4T*THIS%SALP1X+(THIS%TA0T*THIS%EAD4PT+THIS%EAB9T)*THIS%SALP&
        +THIS%EAC1T*THIS%SGE1X+THIS%EAC2T*THIS%SGZ1X+(THIS%GEJT+THIS%TA0T*THIS%EAC2T)*THIS%SGE+(THIS%GZJT-THIS%TA0T*THIS%EAC1T)*THIS%SGZ

    TX3=SIN(THIS%BTAT)*COS(THIS%BTAT)*SXBP
    TX5=FABSC(MYBP,-MZBP,THIS%BTAT)
    TX7=COS(THIS%BTAT)*COS(THIS%BTAT)*SXBP
    TX8=SIN(THIS%BTAT)*SIN(THIS%BTAT)*SXBP
    TX10=FABSC(MZBP,MYBP,THIS%BTAT)
    
!>+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    RLGT=0.0D0
    I=1
    J=1

    K11NLC1=VXB
    K11NLC2=THIS%EAB1B*COS(THIS%BTAT)*TX1+TX2*THIS%SPH
    K11NLC3=-(0.5*THIS%EAEAB*THIS%SV1X+TX3)
    K11NLC4=-TX3
    RLGT(I:I+NAD-1,J:J+NAD-1)=K11NLC1*THIS%FCPFCP(:,:)+K11NLC2*THIS%FCPPFCPP(:,:)+K11NLC3*THIS%FCPPFCP(:,:)+K11NLC4*TRANSPOSE(THIS%FCPPFCP(:,:))
    J=J+NAD

    K12NLC1=THIS%EAB1B*SIN(THIS%BTAT)*TX1+TX4*THIS%SPH
    K12NLC2=-0.5*THIS%EAEAB*THIS%SW1X+TX7
    K12NLC3=-TX8
    RLGT(I:I+NAD-1,J:J+NAD-1)=K12NLC1*THIS%FCPPFCPP(:,:)+K12NLC2*THIS%FCPPFCP(:,:)+K12NLC3*TRANSPOSE(THIS%FCPPFCP(:,:))
    J=J+NAD

    K13NLC=TX5
    RLGT(I:I+NAD-1,J:J+NBD-1)=K13NLC*THIS%FCPPFQ(:,:)

    !->++++++++++++++

    I=I+NAD
    J=1

    K21NLC1=THIS%EAB2B*COS(THIS%BTAT)*TX1-TX6*THIS%SPH
    K21NLC2=-(0.5*THIS%EAZAB*THIS%SV1X+TX8)
    K21NLC3=TX7
    RLGT(I:I+NAD-1,J:J+NAD-1)=K21NLC1*THIS%FCPPFCPP(:,:)+K21NLC2*THIS%FCPPFCP(:,:)+K21NLC3*TRANSPOSE(THIS%FCPPFCP(:,:))
    J=J+NAD

    K22NLC1=VXB
    K22NLC2=THIS%EAB2B*SIN(THIS%BTAT)*TX1+TX9*THIS%SPH
    K22NLC3=-0.5*THIS%EAZAB*THIS%SW1X+TX3
    K22NLC4=TX3
    RLGT(I:I+NAD-1,J:J+NAD-1)=K22NLC1*THIS%FCPFCP(:,:)+K22NLC2*THIS%FCPPFCPP(:,:)+K22NLC3*THIS%FCPPFCP(:,:)+K22NLC4*TRANSPOSE(THIS%FCPPFCP(:,:))
    J=J+NAD

    K23NLC=TX10
    RLGT(I:I+NAD-1,J:J+NBD-1)=K23NLC*THIS%FCPPFQ(:,:)

    !->++++++++++++++

    I=I+NAD
    J=1

    K31NLC1=TX5
    K31NLC2=-THIS%GJT*COS(THIS%BTAT)*TX1+THIS%EAB2B*THIS%SPH
    K31NLC3=0.5*THIS%EAB0T*THIS%SV1X
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K31NLC1*THIS%FCPPFQ(:,:)+K31NLC2*THIS%FCPPFQP(:,:)+K31NLC3*THIS%FCPFQP(:,:))
    J=J+NAD

    K32NLC1=TX10
    K32NLC2=-THIS%GJT*SIN(THIS%BTAT)*TX1-THIS%EAB1B*THIS%SPH
    K32NLC3=0.5*THIS%EAB0T*THIS%SW1X
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K32NLC1*THIS%FCPPFQ(:,:)+K32NLC2*THIS%FCPPFQP(:,:)+K32NLC3*THIS%FCPFQP(:,:))
    J=J+NAD

    K33NLC=0.5*THIS%EAB4T*THIS%SPH1X+TXB
    RLGT(I:I+NBD-1,J:J+NBD-1)=K33NLC*THIS%FQPFQP(:,:)

    !->++++++++++++++

    I=I+NBD
    J=1

    K41NLC1=-THIS%EAB0T*COS(THIS%BTAT)*TX1+THIS%EAZAB*THIS%SPH
    K41NLC2=0.5*THIS%EAT*THIS%SV1X
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K41NLC1*THIS%FCPPFQP(:,:)+K41NLC2*THIS%FCPFQP(:,:))
    J=J+NAD


    K42NLC1=-THIS%EAB0T*SIN(THIS%BTAT)*TX1-THIS%EAEAB*THIS%SPH
    K42NLC2=0.5*THIS%EAT*THIS%SW1X
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K42NLC1*THIS%FCPPFQP(:,:)+K42NLC2*THIS%FCPFQP(:,:))
    J=J+NAD

    K43NLC=0.5*THIS%EAC0T*THIS%SPH1X
    RLGT(I:I+NBD-1,J:J+NBD-1)=K43NLC*THIS%FQPFQP(:,:)

    !->++++++++++++++

    I=I+NBD
    J=1

    K51NLC1=0.5*THIS%EAD0T*THIS%SV1X
    K51NLC2=THIS%EAD2B*THIS%SPH
    K51NLC3=0.5*(THIS%TA0T*THIS%EAD0PT+THIS%EAB5T)*THIS%SV1X
    K51NLC4=-THIS%EAB14T*COS(THIS%BTAT)*TX1+(THIS%TA0T*THIS%EAD2PB+THIS%EAB7B)*THIS%SPH
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K51NLC1*THIS%FCPFQP(:,:)+K51NLC2*THIS%FCPPFQP(:,:)+K51NLC3*THIS%FCPFQ(:,:)+K51NLC4*THIS%FCPPFQ(:,:))
    J=J+NAD


    K52NLC1=0.5*THIS%EAD0T*THIS%SW1X
    K52NLC2=-THIS%EAD1B*THIS%SPH
    K52NLC3=0.5*(THIS%TA0T*THIS%EAD0PT+THIS%EAB5T)*THIS%SW1X
    K52NLC4=-THIS%EAB14T*SIN(THIS%BTAT)*TX1-(THIS%TA0T*THIS%EAD1PB+THIS%EAB6B)*THIS%SPH
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K52NLC1*THIS%FCPFQP(:,:)+K52NLC2*THIS%FCPPFQP(:,:)+K52NLC3*THIS%FCPFQ(:,:)+K52NLC4*THIS%FCPPFQ(:,:))
    J=J+NAD


    K53NLC1=0.5*THIS%EAD4T*THIS%SPH1X
    K53NLC2=0.5*(THIS%TA0T*THIS%EAD4PT+THIS%EAB9T)*THIS%SPH1X
    RLGT(I:I+NBD-1,J:J+NBD-1)=K53NLC1*THIS%FQPFQP(:,:)+TRANSPOSE(K53NLC2*THIS%FQPFQ(:,:))

    !->++++++++++++++

    I=I+NBD
    J=1

    K61NLC1=-THIS%EAB12T*COS(THIS%BTAT)*TX1+THIS%GEAZBB*THIS%SPH
    K61NLC2=0.5*THIS%EAEAT*THIS%SV1X
    K61NLC3=0.5*(THIS%GEAT+THIS%TA0T*THIS%EAZAT)*THIS%SV1X
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K61NLC1*THIS%FCPPFQ(:,:)+K61NLC2*THIS%FCPFQP(:,:)+K61NLC3*THIS%FCPFQ(:,:))
    J=J+NAD


    K62NLC1=-THIS%EAB12T*SIN(THIS%BTAT)*TX1-THIS%GEAEBB*THIS%SPH
    K62NLC2=0.5*THIS%EAEAT*THIS%SW1X
    K62NLC3=0.5*(THIS%GEAT+THIS%TA0T*THIS%EAZAT)*THIS%SW1X
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K62NLC1*THIS%FCPPFQ(:,:)+K62NLC2*THIS%FCPFQP(:,:)+K62NLC3*THIS%FCPFQ(:,:))
    J=J+NAD

    K63NLC=0.5*THIS%GEJT*THIS%SPH1X
    RLGT(I:I+NBD-1,J:J+NBD-1)=TRANSPOSE(K63NLC*THIS%FQPFQ(:,:))

    !->++++++++++++++

    I=I+NBD
    J=1

    K71NLC1=-THIS%EAB10T*COS(THIS%BTAT)*TX1+THIS%GZAZCB*THIS%SPH
    K71NLC2=0.5*THIS%EAZAT*THIS%SV1X
    K71NLC3=0.5*(THIS%GZAT-THIS%TA0T*THIS%EAEAT)*THIS%SV1X
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K71NLC1*THIS%FCPPFQ(:,:)+K71NLC2*THIS%FCPFQP(:,:)+K71NLC3*THIS%FCPFQ(:,:))
    J=J+NAD


    K72NLC1=-THIS%EAB10T*SIN(THIS%BTAT)*TX1-THIS%GZAECB*THIS%SPH
    K72NLC2=0.5*THIS%EAZAT*THIS%SW1X
    K72NLC3=0.5*(THIS%GZAT-THIS%TA0T*THIS%EAEAT)*THIS%SW1X
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K72NLC1*THIS%FCPPFQ(:,:)+K72NLC2*THIS%FCPFQP(:,:)+K72NLC3*THIS%FCPFQ(:,:))
    J=J+NAD


    K73NLC=0.5*THIS%GZJT*THIS%SPH1X
    RLGT(I:I+NBD-1,J:J+NBD-1)=TRANSPOSE(K73NLC*THIS%FQPFQ(:,:))

END SUBROUTINE

SUBROUTINE KFCFX(THIS,RLGT,FCF)      
IMPLICIT NONE 
CLASS(ELEMENT) :: THIS
REAL(RDT),INTENT(OUT):: RLGT(THIS%SMD,THIS%SMD),FCF(THIS%SMD)

INTEGER I,J
INTEGER :: SMD,NAD,NBD

REAL(RDT) TX1,TX2,TX3
REAL(RDT) TX4,TX5,TX6

REAL(RDT) K11CF1,K11CF2,K11CF3,K12CF1,K12CF2,K12CF3,K12CF4,K13CF1,K13CF2
REAL(RDT) K14CF1,K14CF2,K15CF1,K15CF2,K16CF1,K16CF2,K17CF1,K17CF2
REAL(RDT) K21CF1,K21CF2,K21CF3,K21CF4,K22CF1,K22CF2,K22CF3,K23CF1,K23CF2
REAL(RDT) K24CF1,K24CF2,K25CF1,K25CF2,K26CF1,K26CF2,K27CF1,K27CF2
REAL(RDT) K31CF1,K31CF2,K32CF1,K32CF2,K33CF,K34CF,K35CF,K36CF,K37CF
REAL(RDT) K41CF1,K41CF2,K42CF1,K42CF2,K43CF,K44CF,K45CF,K46CF,K47CF
REAL(RDT) K51CF1,K51CF2,K52CF1,K52CF2,K53CF,K55CF,K56CF,K57CF
REAL(RDT) K61CF1,K61CF2,K62CF1,K62CF2,K63CF,K66CF,K67CF
REAL(RDT) K71CF1,K71CF2,K72CF1,K72CF2,K73CF,K77CF

REAL(RDT) F1CFC1,F1CFC2,F2CFC1,F2CFC2,F3CFC
REAL(RDT) F4CFC,F5CFC,F6CFC,F7CFC

    !->++++++++++++++
    SMD=THIS%SMD
    NAD=THIS%NAD
    NBD=THIS%NBD

    TX1=SIN(THIS%BTAT)*COS(THIS%BTAT)
    TX2=COS(THIS%BTAT)**2-SIN(THIS%BTAT)**2
    TX3=(THIS%IMZZT-THIS%IMEET)*TX1+THIS%IMEZT*TX2
    TX4=THIS%IMZZT*COS(THIS%BTAT)**2+THIS%IMEET*SIN(THIS%BTAT)**2-2*THIS%IMEZT*TX1
    TX5=THIS%IMEET*COS(THIS%BTAT)**2+THIS%IMZZT*SIN(THIS%BTAT)**2+2*THIS%IMEZT*TX1
    TX6=(THIS%IMZZT-THIS%IMEET)*TX2-4*THIS%IMEZT*TX1  


    !>++++++++++++++++++
    
    RLGT=0.0D0
    I=1
    J=1

    K11CF1=-THIS%TV1(2)*THIS%MSLT
    K11CF2=-THIS%TV3(2)*THIS%MEMB
    K11CF3=-THIS%TV2(1)*THIS%MEMB
    RLGT(I:I+NAD-1,J:J+NAD-1)=K11CF1*THIS%FCFC(:,:)+K11CF2*TRANSPOSE(THIS%FCPFC(:,:))+K11CF3*THIS%FCPFC(:,:)
    J=J+NAD

    K12CF1=THIS%TV2(2)*THIS%MSLT
    K12CF2=-THIS%TV3(1)*THIS%MEMB
    K12CF3=-THIS%TV3(2)*THIS%MZMB
    K12CF4=(THIS%HOMGB(2)-THIS%TV3(2)*THIS%XX)*THIS%MZMT*COS(THIS%BTAT)**3
    RLGT(I:I+NAD-1,J:J+NAD-1)=K12CF1*THIS%FCFC(:,:)+K12CF2*THIS%FCPFC(:,:)+K12CF3*TRANSPOSE(THIS%FCPFC(:,:))+K12CF4*THIS%FCPFCP(:,:)
    J=J+NAD

    K13CF1=THIS%TV2(2)*THIS%MEMB+THIS%TV1(2)*THIS%MZMB
    K13CF2=-(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MZMB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K13CF1*THIS%FCFQ(:,:)+K13CF2*THIS%FCPFQ(:,:)
    J=J+NBD

    K14CF1=THIS%TV3(2)*THIS%MSLT
    K14CF2=THIS%TV1(1)*THIS%MEMB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K14CF1*THIS%FCFQ(:,:)+K14CF2*THIS%FCPFQ(:,:)
    J=J+NBD

    K15CF1=THIS%TV3(2)*THIS%MD0T
    K15CF2=THIS%TV1(1)*THIS%MD1B
    RLGT(I:I+NAD-1,J:J+NBD-1)=K15CF1*THIS%FCFQ(:,:)+K15CF2*THIS%FCPFQ(:,:)
    J=J+NBD

    K16CF1=THIS%TV3(2)*THIS%MEMT
    K16CF2=THIS%TV1(1)*THIS%IMZZB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K16CF1*THIS%FCFQ(:,:)+K16CF2*THIS%FCPFQ(:,:)
    J=J+NBD

    K17CF1=THIS%TV3(2)*THIS%MZMT
    K17CF2=THIS%TV1(1)*THIS%IMEZB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K17CF1*THIS%FCFQ(:,:)+K17CF2*THIS%FCPFQ(:,:)

    !---------------

    I=I+NAD
    J=1

    K21CF1=THIS%TV3(3)*THIS%MSLT
    K21CF2=-THIS%TV2(3)*THIS%MEMB
    K21CF3=-THIS%TV2(1)*THIS%MZMB
    K21CF4=(THIS%HOMGB(2)-THIS%TV3(2)*THIS%XX)*THIS%MZMT*COS(THIS%BTAT)**3
    RLGT(I:I+NAD-1,J:J+NAD-1)=K21CF1*THIS%FCFC(:,:)+K21CF2*TRANSPOSE(THIS%FCPFC(:,:))+K21CF3*THIS%FCPFC(:,:)+K21CF4*THIS%FCPFCP(:,:)
    J=J+NAD

    K22CF1=-THIS%TV1(3)*THIS%MSLT
    K22CF2=-THIS%TV2(3)*THIS%MZMB
    K22CF3=-THIS%TV3(1)*THIS%MZMB
    RLGT(I:I+NAD-1,J:J+NAD-1)=K22CF1*THIS%FCFC(:,:)+K22CF2*TRANSPOSE(THIS%FCPFC(:,:))+K22CF3*THIS%FCPFC(:,:)
    J=J+NAD

    K23CF1=-(THIS%TV3(3)*THIS%MZMB+THIS%TV1(3)*THIS%MEMB)
    K23CF2=(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MEMB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K23CF1*THIS%FCFQ(:,:)+K23CF2*THIS%FCPFQ(:,:)
    J=J+NBD

    K24CF1=THIS%TV2(3)*THIS%MSLT
    K24CF2=THIS%TV1(1)*THIS%MZMB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K24CF1*THIS%FCFQ(:,:)+K24CF2*THIS%FCPFQ(:,:)
    J=J+NBD

    K25CF1=THIS%TV2(3)*THIS%MD0T
    K25CF2=THIS%TV1(1)*THIS%MD2B
    RLGT(I:I+NAD-1,J:J+NBD-1)=K25CF1*THIS%FCFQ(:,:)+K25CF2*THIS%FCPFQ(:,:)
    J=J+NBD

    K26CF1=THIS%TV2(3)*THIS%MEMT
    K26CF2=THIS%TV1(1)*THIS%IMZEB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K26CF1*THIS%FCFQ(:,:)+K26CF2*THIS%FCPFQ(:,:)
    J=J+NBD

    K27CF1=THIS%TV2(3)*THIS%MZMT
    K27CF2=THIS%TV1(1)*THIS%IMEEB
    RLGT(I:I+NAD-1,J:J+NBD-1)=K27CF1*THIS%FCFQ(:,:)+K27CF2*THIS%FCPFQ(:,:)

    !---------------

    I=I+NAD
    J=1

    K31CF1=THIS%TV3(3)*THIS%MEMB+THIS%TV1(2)*THIS%MZMB
    K31CF2=-(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MZMB
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K31CF1*THIS%FCFQ(:,:)+K31CF2*THIS%FCPFQ(:,:))
    J=J+NAD

    K32CF1=-(THIS%TV2(2)*THIS%MZMB+THIS%TV1(3)*THIS%MEMB)
    K32CF2=(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MEMB
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K32CF1*THIS%FCFQ(:,:)+K32CF2*THIS%FCPFQ(:,:))
    J=J+NAD

!   K33CF=(THIS%IMEET+THIS%IMZZT)*THIS%OMGE(1)**2+2*THIS%OMGE(2)*THIS%OMGE(3)*TX3&
!            +THIS%OMGE(2)**2*TX4+THIS%OMGE(3)**2*TX5
!      K33CF=-K33CF
            K33CF=(THIS%OMGE(3)**2-THIS%OMGE(2)**2)*TX6-4*THIS%OMGE(2)*THIS%OMGE(3)*TX3
            RLGT(I:I+NBD-1,J:J+NBD-1)=K33CF*THIS%FQFQ(:,:)
    J=J+NBD

    K34CF=THIS%TV2(3)*THIS%MEMB-THIS%TV3(2)*THIS%MZMB
    RLGT(I:I+NBD-1,J:J+NBD-1)=K34CF*THIS%FQFQ(:,:)
    J=J+NBD

    K35CF=THIS%TV2(3)*THIS%MD1B-THIS%TV3(2)*THIS%MD2B
    RLGT(I:I+NBD-1,J:J+NBD-1)=K35CF*THIS%FQFQ(:,:)
    J=J+NBD

    K36CF=THIS%TV2(3)*THIS%IMZZB-THIS%TV3(2)*THIS%IMZEB
    RLGT(I:I+NBD-1,J:J+NBD-1)=K36CF*THIS%FQFQ(:,:)
    J=J+NBD

    K37CF=THIS%TV2(3)*THIS%IMEZB-THIS%TV3(2)*THIS%IMEEB
    RLGT(I:I+NBD-1,J:J+NBD-1)=K37CF*THIS%FQFQ(:,:)

    !---------------

    I=I+NBD
    J=1

    K41CF1=THIS%TV2(1)*THIS%MSLT
    K41CF2=THIS%TV1(1)*THIS%MEMB
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K41CF1*THIS%FCFQ(:,:)+K41CF2*THIS%FCPFQ(:,:))
    J=J+NAD

    K42CF1=THIS%TV3(1)*THIS%MSLT
    K42CF2=THIS%TV1(1)*THIS%MZMB
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K42CF1*THIS%FCFQ(:,:)+K42CF2*THIS%FCPFQ(:,:))
    J=J+NAD

    K43CF=THIS%TV3(1)*THIS%MEMB-THIS%TV2(1)*THIS%MZMB
    RLGT(I:I+NBD-1,J:J+NBD-1)=K43CF*THIS%FQFQ(:,:)
    J=J+NBD

    K44CF=-THIS%TV1(1)*THIS%MSLT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K44CF*THIS%FQFQ(:,:)
    J=J+NBD

    K45CF=-THIS%TV1(1)*THIS%MD0T
    RLGT(I:I+NBD-1,J:J+NBD-1)=K45CF*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    J=J+NBD

    K46CF=-THIS%TV1(1)*THIS%MEMT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K46CF*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    J=J+NBD

    K47CF=-THIS%TV1(1)*THIS%MZMT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K47CF*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

      !---------------

    I=I+NBD
    J=1

    K51CF1=THIS%TV2(1)*THIS%MD0T
    K51CF2=THIS%TV1(1)*THIS%MD1B
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K51CF1*THIS%FCFQ(:,:)+K51CF2*THIS%FCPFQ(:,:))
    J=J+NAD

    K52CF1=THIS%TV3(1)*THIS%MD0T
    K52CF2=THIS%TV1(1)*THIS%MD2B
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K52CF1*THIS%FCFQ(:,:)+K52CF2*THIS%FCPFQ(:,:))
    J=J+NAD

    K53CF=THIS%TV3(1)*THIS%MD1B-THIS%TV2(1)*THIS%MD2B
    RLGT(I:I+NBD-1,J:J+NBD-1)=K53CF*THIS%FQFQ(:,:)
    J=J+NBD

    J=J+NBD

    K55CF=-THIS%TV1(1)*THIS%MD3T
    RLGT(I:I+NBD-1,J:J+NBD-1)=K55CF*THIS%FQFQ(:,:)
    J=J+NBD

    K56CF=-THIS%TV1(1)*THIS%MD1T
    RLGT(I:I+NBD-1,J:J+NBD-1)=K56CF*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))
    J=J+NBD

    K57CF=-THIS%TV1(1)*THIS%MD2T
    RLGT(I:I+NBD-1,J:J+NBD-1)=K57CF*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

    !---------------

    I=I+NBD
    J=1

    K61CF1=THIS%TV2(1)*THIS%MEMT
    K61CF2=THIS%TV1(1)*THIS%IMZZB
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K61CF1*THIS%FCFQ(:,:)+K61CF2*THIS%FCPFQ(:,:))
    J=J+NAD

    K62CF1=THIS%TV3(1)*THIS%MEMT
    K62CF2=THIS%TV1(1)*THIS%IMZEB
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K62CF1*THIS%FCFQ(:,:)+K62CF2*THIS%FCPFQ(:,:))
    J=J+NAD

    K63CF=THIS%TV3(1)*THIS%IMZZB-THIS%TV2(1)*THIS%IMZEB
    RLGT(I:I+NBD-1,J:J+NBD-1)=K63CF*THIS%FQFQ(:,:)
    J=J+NBD

    J=J+NBD

    J=J+NBD

    K66CF=-THIS%TV1(1)*THIS%IMZZT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K66CF*THIS%FQFQ(:,:)
    J=J+NBD

    K67CF=-THIS%TV1(1)*THIS%IMEZT
    RLGT(I:I+NBD-1,J:J+NBD-1)=K67CF*THIS%FQFQ(:,:)
    RLGT(J:J+NBD-1,I:I+NBD-1)=TRANSPOSE(RLGT(I:I+NBD-1,J:J+NBD-1))

    !---------------

    I=I+NBD
    J=1

    K71CF1=THIS%TV2(1)*THIS%MZMT
    K71CF2=THIS%TV1(1)*THIS%IMEZB
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K71CF1*THIS%FCFQ(:,:)+K71CF2*THIS%FCPFQ(:,:))
    J=J+NAD

    K72CF1=THIS%TV3(1)*THIS%MZMT
    K72CF2=THIS%TV1(1)*THIS%IMEEB
    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(K72CF1*THIS%FCFQ(:,:)+K72CF2*THIS%FCPFQ(:,:))
    J=J+NAD

    K73CF=THIS%TV3(1)*THIS%IMEZB-THIS%TV2(1)*THIS%IMEEB
    RLGT(I:I+NBD-1,J:J+NBD-1)=K73CF*THIS%FQFQ(:,:)
    J=J+NBD

    J=J+NBD

    J=J+NBD

    J=J+NBD

    K77CF=-THIS%TV1(1)*THIS%IMEET
    RLGT(I:I+NBD-1,J:J+NBD-1)=K77CF*THIS%FQFQ(:,:)

    !>++++++++++++++++++

    FCF=0.0D0
    I=1

    F1CFC1=-(THIS%HOMGB(2)-THIS%TV3(2)*THIS%XX)*THIS%MSLT-THIS%TV1(2)*THIS%MEMB+THIS%TV2(2)*THIS%MZMB
    F1CFC2=(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MEMB-THIS%TV2(1)*TX4-THIS%TV3(1)*TX3
    FCF(I:I+NAD-1)=F1CFC1*THIS%TPC+F1CFC2*THIS%TPC1D
    I=I+NAD

    F2CFC1=-(THIS%HOMGB(3)-THIS%TV2(3)*THIS%XX)*THIS%MSLT-THIS%TV1(3)*THIS%MZMB+THIS%TV3(3)*THIS%MEMB
    F2CFC2=(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MZMB-THIS%TV2(1)*TX3-THIS%TV3(1)*TX5
    FCF(I:I+NAD-1)=F2CFC1*THIS%TPC+F2CFC2*THIS%TPC1D
    I=I+NAD

    F3CFC=-(THIS%HOMGB(3)-THIS%TV2(3)*THIS%XX)*THIS%MEMB+(THIS%HOMGB(2)-THIS%TV3(2)*THIS%XX)*THIS%MZMB+(THIS%IMEET+THIS%IMZZT)*THIS%OMGE1D(1)&
            -(THIS%OMGE(2)**2-THIS%OMGE(3)**2)*TX3+THIS%OMGE(2)*THIS%OMGE(3)*TX6
    FCF(I:I+NBD-1)=F3CFC*THIS%TPQ
    I=I+NBD


    F4CFC=-(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MSLT+THIS%TV2(1)*THIS%MEMB+THIS%TV3(1)*THIS%MZMB
    FCF(I:I+NBD-1)=F4CFC*THIS%TPQ
    I=I+NBD

    F5CFC=-(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MD0T+THIS%TV2(1)*THIS%MD1B+THIS%TV3(1)*THIS%MD2B
    FCF(I:I+NBD-1)=F5CFC*THIS%TPQ
    I=I+NBD

    F6CFC=-(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MEMT+THIS%TV2(1)*THIS%IMZZB+THIS%TV3(1)*THIS%IMZEB
    FCF(I:I+NBD-1)=F6CFC*THIS%TPQ
    I=I+NBD

    F7CFC=-(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%MZMT+THIS%TV2(1)*THIS%IMEZB+THIS%TV3(1)*THIS%IMEEB
    FCF(I:I+NBD-1)=F7CFC*THIS%TPQ


END SUBROUTINE
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE KFIX(THIS,RLGT,FI,PE,QE)
IMPLICIT NONE
CLASS(ELEMENT) :: THIS
REAL(RDT),INTENT(IN)::PE(3),QE(3)
REAL(RDT),INTENT(OUT)::RLGT(THIS%SMD,THIS%SMD),FI(THIS%SMD)

INTEGER I,J
INTEGER :: SMD,NAD,NBD
    !->++++++++++++++
    SMD=THIS%SMD
    NAD=THIS%NAD
    NBD=THIS%NBD

    RLGT=0.0D0
    I=1
    J=1

    J=J+NAD

    RLGT(I:I+NAD-1,J:J+NAD-1)=QE(1)*THIS%FCPFCP(:,:)
    RLGT(J:J+NAD-1,I:I+NAD-1)=-RLGT(I:I+NAD-1,J:J+NAD-1)

    I=I+2*NAD
    J=1

    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(-QE(2)*THIS%FCPFQ(:,:))

    J=J+NAD

    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(-QE(3)*THIS%FCPFQ(:,:))

    I=I+NBD
    J=1

    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(QE(3)*THIS%FCPFQP(:,:))

    J=J+NAD

    RLGT(I:I+NBD-1,J:J+NAD-1)=TRANSPOSE(-QE(2)*THIS%FCPFQP(:,:))


    !>++++++++++++++++++++

    FI=0.0D0
    I=1

    FI(I:I+NAD-1)=-PE(2)*THIS%TPC-QE(3)*THIS%TPC1D
    I=I+NAD

    FI(I:I+NAD-1)=-PE(3)*THIS%TPC+QE(2)*THIS%TPC1D
    I=I+NAD

    FI(I:I+NBD-1)=-QE(1)*THIS%TPQ
    I=I+NBD

    FI(I:I+NBD-1)=-PE(1)*THIS%TPQ

END SUBROUTINE
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE FMINT(THIS,FCT,MTT)
IMPLICIT NONE
CLASS(ELEMENT) :: THIS
REAL(RDT),INTENT(OUT)::FCT(3),MTT(3)

REAL(RDT) :: TX1,TX2,TX3,TX4,TX5,TX6

REAL(RDT) :: TM1(3,3)

REAL(RDT) :: ZUB, ZVB, ZWB, ZVPB, ZWPB, ZPHB, ZETB, ZZTB
REAL(RDT) :: FFE(3), MME(3), MMD(3), VTP1(3)

REAL(RDT) :: TER(3,3)
REAL(RDT) :: TDE(3,3), TDE1T(3,3),ZERO=0.0
    
    TX1=SIN(THIS%BTAT)*COS(THIS%BTAT)
    TX2=COS(THIS%BTAT)**2-SIN(THIS%BTAT)**2
    TX3=(THIS%IMZZT-THIS%IMEET)*TX1+THIS%IMEZT*TX2
    TX4=THIS%IMZZT*COS(THIS%BTAT)**2+THIS%IMEET*SIN(THIS%BTAT)**2-2*THIS%IMEZT*TX1
    TX5=THIS%IMEET*COS(THIS%BTAT)**2+THIS%IMZZT*SIN(THIS%BTAT)**2+2*THIS%IMEZT*TX1
    TX6=(THIS%IMZZT-THIS%IMEET)*TX2-4*THIS%IMEZT*TX1  

    ZUB= THIS%MZMB*(-THIS%TV3(1)-THIS%TV1(1)*THIS%SW1X+THIS%TV2(1)*THIS%SPH+THIS%SW1X2T-2.0*THIS%OMGE(3)*THIS%SPH1T) &
        +THIS%MEMB*(-THIS%TV2(1)-THIS%TV1(1)*THIS%SV1X-THIS%TV3(1)*THIS%SPH+THIS%SV1X2T-2.0*THIS%OMGE(2)*THIS%SPH1T) &
        -THIS%MSLT*(-THIS%HOMGB(1)+THIS%SU2T-2.0*THIS%OMGE(3)*THIS%SV1T+2.0*THIS%OMGE(2)*THIS%SW1T-THIS%TV1(1)*(THIS%XX+THIS%SU)+THIS%TV2(1)*THIS%SV+THIS%TV3(1)*THIS%SW) & 
        -THIS%MD0T*(THIS%SALP2T-THIS%TV1(1)*THIS%SALP)-THIS%MEMT*(THIS%SGE2T-THIS%TV1(1)*THIS%SGE)-THIS%MZMT*(THIS%SGZ2T-THIS%TV1(1)*THIS%SGZ)

    ZVB= THIS%MZMB*(-THIS%TV2(2)+THIS%TV3(2)*THIS%SW1X-THIS%TV1(2)*THIS%SPH+THIS%SPH2T+2.0*THIS%OMGE(3)*THIS%SW1X1T) &
        +THIS%MEMB*(THIS%TV1(2)-THIS%TV2(2)*THIS%SPH+THIS%TV3(2)*THIS%SV1X+2.0*THIS%OMGE(3)*THIS%SV1X1T+2.0*THIS%OMGE(1)*THIS%SPH1T) &
        -THIS%MSLT*(-THIS%HOMGB(2)+THIS%SV2T+2.0*THIS%OMGE(3)*THIS%SU1T-2.0*THIS%OMGE(1)*THIS%SW1T+THIS%TV3(2)*(THIS%XX+THIS%SU)-THIS%TV1(2)*THIS%SV+THIS%TV2(2)*THIS%SW) & 
        -THIS%MD0T*(2.0*THIS%OMGE(3)*THIS%SALP1T+THIS%TV3(2)*THIS%SALP)-THIS%MEMT*(2.0*THIS%OMGE(3)*THIS%SGE1T+THIS%TV3(2)*THIS%SGE)-THIS%MZMT*(2.0*THIS%OMGE(3)*THIS%SGZ1T+THIS%TV3(2)*THIS%SGZ)

    ZWB= THIS%MZMB*(THIS%TV1(3)+THIS%TV2(3)*THIS%SW1X+THIS%TV3(3)*THIS%SPH-2.0*THIS%OMGE(2)*THIS%SW1X1T+2.0*THIS%OMGE(1)*THIS%SPH1T) &
        -THIS%MEMB*(THIS%TV3(3)-THIS%TV1(3)*THIS%SPH-THIS%TV2(3)*THIS%SV1X+2.0*THIS%OMGE(2)*THIS%SV1X1T+THIS%SPH2T) &
        -THIS%MSLT*(-THIS%HOMGB(3)+THIS%SW2T-2.0*THIS%OMGE(2)*THIS%SU1T+2.0*THIS%OMGE(1)*THIS%SV1T+THIS%TV2(3)*(THIS%XX+THIS%SU)+THIS%TV3(3)*THIS%SV-THIS%TV1(3)*THIS%SW) & 
        +THIS%MD0T*(2.0*THIS%OMGE(2)*THIS%SALP1T-THIS%TV2(3)*THIS%SALP)+THIS%MEMT*(2.0*THIS%OMGE(2)*THIS%SGE1T-THIS%TV2(3)*THIS%SGE)+THIS%MZMT*(2.0*THIS%OMGE(2)*THIS%SGZ1T-THIS%TV2(3)*THIS%SGZ)

    ZVPB=THIS%MZMB*(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%SPH &
        +THIS%MEMB*(-THIS%HOMGB(1)-2.0*THIS%OMGE(3)*THIS%SV1T+2.0*THIS%OMGE(2)*THIS%SW1T-THIS%TV1(1)*(THIS%XX+THIS%SU)+THIS%TV2(1)*THIS%SV+THIS%TV3(1)*THIS%SW+THIS%SU2T) &
        +THIS%MD1B*(THIS%SALP2T-THIS%TV1(1)*THIS%SALP)+THIS%IMZZB*(THIS%SGE2T-THIS%TV1(1)*THIS%SGE)+THIS%IMEZB*(THIS%SGZ2T-THIS%TV1(1)*THIS%SGZ) &
        +THIS%TV2(1)*TX4+THIS%TV3(1)*TX3+THIS%MZMT*COS(THIS%BTAT)**3*(-THIS%HOMGB(2)+THIS%TV3(2)*THIS%XX)*THIS%SW1X

    ZWPB=THIS%MZMB*(-THIS%HOMGB(1)-2.0*THIS%OMGE(3)*THIS%SV1T+2.0*THIS%OMGE(2)*THIS%SW1T-THIS%TV1(1)*(THIS%XX+THIS%SU)+THIS%TV2(1)*THIS%SV+THIS%TV3(1)*THIS%SW+THIS%SU2T) &
        -THIS%MEMB*(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%SPH &
        +THIS%MD2B*(THIS%SALP2T-THIS%TV1(1)*THIS%SALP)+THIS%IMZEB*(THIS%SGE2T-THIS%TV1(1)*THIS%SGE)+THIS%IMEEB*(THIS%SGZ2T-THIS%TV1(1)*THIS%SGZ) &
        +THIS%TV2(1)*TX3+THIS%TV3(1)*TX5+THIS%MZMT*COS(THIS%BTAT)**3*(-THIS%HOMGB(2)+THIS%TV3(2)*THIS%XX)*THIS%SV1X

    ZPHB=THIS%MZMB*(THIS%SV2T+2.0*THIS%OMGE(3)*THIS%SU1T-2.0*THIS%OMGE(1)*THIS%SW1T-THIS%HOMGB(2)+THIS%TV3(2)*(THIS%XX+THIS%SU)-THIS%TV1(2)*THIS%SV+THIS%TV2(2)*THIS%SW) &
        +THIS%MZMB*(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%SV1X & 
        -THIS%MEMB*(THIS%SW2T-2.0*THIS%OMGE(2)*THIS%SU1T+2.0*THIS%OMGE(1)*THIS%SV1T-THIS%HOMGB(3)+THIS%TV2(3)*(THIS%XX+THIS%SU)+THIS%TV3(3)*THIS%SV-THIS%TV1(3)*THIS%SW) &
        -THIS%MEMB*(THIS%HOMGB(1)+THIS%TV1(1)*THIS%XX)*THIS%SW1X & 
        +THIS%MD2B*(2.0*THIS%OMGE(3)*THIS%SALP1T+THIS%TV3(2)*THIS%SALP)+THIS%IMZEB*(2.0*THIS%OMGE(3)*THIS%SGE1T+THIS%TV3(2) *THIS%SGE)+THIS%IMEEB*(2.0*THIS%OMGE(3)*THIS%SGZ1T+THIS%TV3(2)*THIS%SGZ) &
        +THIS%MD1B*(2.0*THIS%OMGE(2)*THIS%SALP1T-THIS%TV2(3)*THIS%SALP)+THIS%IMZZB*(2.0*THIS%OMGE(2)*THIS%SGE1T-THIS%TV2(3) *THIS%SGE)+THIS%IMEZB*(2.0*THIS%OMGE(2)*THIS%SGZ1T-THIS%TV2(3)*THIS%SGZ) &
        -(THIS%IMEET+THIS%IMZZT)*(THIS%SPH2T+THIS%OMGE1D(1))+(THIS%OMGE(2)**2-THIS%OMGE(3)**2)*TX3-THIS%OMGE(2)*THIS%OMGE(3)*TX6 &
        +(THIS%IMEET+THIS%IMZZT)*THIS%OMGE(1)**2*THIS%SPH &
        +(2*THIS%OMGE(2)*THIS%OMGE(3)*TX3+THIS%OMGE(2)**2*TX4+THIS%OMGE(3)**2*TX5)*THIS%SPH
      
    ZETB=THIS%IMZEB*(-2.0*THIS%OMGE(3)*THIS%SPH1T+THIS%SW1X2T-THIS%TV3(1)+THIS%TV2(1)*THIS%SPH-THIS%TV1(1)*THIS%SW1X) &
        +THIS%IMZZB*(-2.0*THIS%OMGE(2)*THIS%SPH1T+THIS%SV1X2T-THIS%TV2(1)-THIS%TV3(1)*THIS%SPH-THIS%TV1(1)*THIS%SV1X) &
        -THIS%MEMT*(-THIS%HOMGB(1)+THIS%SU2T-2.0*THIS%OMGE(3)*THIS%SV1T+2.0*THIS%OMGE(2)*THIS%SW1T-THIS%TV1(1)*(THIS%XX+THIS%SU)+THIS%TV2(1)*THIS%SV+THIS%TV3(1)*THIS%SW) & 
        -THIS%MD1T*(THIS%SALP2T-THIS%TV1(1)*THIS%SALP)-THIS%IMZZT*(THIS%SGE2T-THIS%TV1(1)*THIS%SGE)-THIS%IMEZT*(THIS%SGZ2T-THIS%TV1(1)*THIS%SGZ) 

    ZZTB=THIS%IMEEB*(-2.0*THIS%OMGE(3)*THIS%SPH1T+THIS%SW1X2T-THIS%TV3(1)+THIS%TV2(1)*THIS%SPH-THIS%TV1(1)*THIS%SW1X) &
        +THIS%IMEZB*(-2.0*THIS%OMGE(2)*THIS%SPH1T+THIS%SV1X2T-THIS%TV2(1)-THIS%TV3(1)*THIS%SPH-THIS%TV1(1)*THIS%SV1X) &
        -THIS%MZMT*(-THIS%HOMGB(1)+THIS%SU2T-2.0*THIS%OMGE(3)*THIS%SV1T+2.0*THIS%OMGE(2)*THIS%SW1T-THIS%TV1(1)*(THIS%XX+THIS%SU)+THIS%TV2(1)*THIS%SV+THIS%TV3(1)*THIS%SW) & 
        -THIS%MD2T*(THIS%SALP2T-THIS%TV1(1)*THIS%SALP)-THIS%IMEZT*(THIS%SGE2T-THIS%TV1(1)*THIS%SGE)-THIS%IMEET*(THIS%SGZ2T-THIS%TV1(1)*THIS%SGZ) 

    FFE=(/ZUB, ZVB, ZWB/)   
    MME=(/ZERO, -ZWPB, ZVPB/)  
    MMD=(/ZPHB, ZZTB, -ZETB/)  
      

    CALL GETTDE(TDE,TDE1T,THIS%BTAT,THIS%SPH,THIS%SPH1T,THIS%SV1X,THIS%SW1X,THIS%SV1X1T,THIS%SW1X1T)
    TM1=TRANSPOSE(TDE)
    CALL MVMU2(VTP1,3,3,TM1,MMD)
      
    MME=MME+VTP1 

    CALL MAMU(TER,3,3,3,THIS%TEB,THIS%TBR)
    TM1=TRANSPOSE(TER)
      
    CALL MVMU2(FCT,3,3,TM1,FFE)
    CALL MVMU2(MTT,3,3,TM1,MME)   
       
END SUBROUTINE FMINT
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE RLCTRFB(THIS,XRRFB,HE,EL1)  
IMPLICIT NONE
CLASS(ELEMENT) :: THIS
REAL(RDT),INTENT(IN)::HE,EL1
REAL(RDT),INTENT(OUT)::XRRFB(3)

REAL(RDT) R0(3) 
REAL(RDT) HEB(3),HER(3)
REAL(RDT) ELE(3), ELB(3)
REAL(RDT) TM1(3,3)

    ELE=(/THIS%XX+THIS%SU, THIS%SV, THIS%SW/)

    TM1=TRANSPOSE(THIS%TEB) 
    CALL MVMU2(ELB,3,3,TM1,ELE)
    
    HEB=HE*(/1.0, 0.0, 0.0/)    
    HEB=HEB+ELB
    
    TM1=TRANSPOSE(THIS%TBR) 
    CALL MVMU2(HER,3,3,TM1,HEB)
    
    R0=EL1*(/1.0, 0.0, 0.0/)    
    XRRFB=HER+R0
    
END SUBROUTINE RLCTRFB

!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> the purpose:
subroutine rvclct(this,rc, vc, dm, npt, cdlct,cho) 
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> modules used:
implicit none
class(element) :: this
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> dummy arguments / interface: 
!-> dm == 3.
!-> uvc0 ==6.
integer, intent(in):: dm, npt
real(rdt), intent(in):: cdlct(dm, npt)
real(rdt), intent(out):: rc(dm, npt), vc(dm, npt)
integer,optional :: cho
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> FUNCTIONS INVOKED:
!->
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> SUBROUTINES INVOKED:
!->       GETTDE, abplsv, VCP     
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> LOCAL VARIABLES:
integer i
real(rdt) rea(dm), veal(dm)
real(rdt) tde(dm, dm), ted(dm, dm), tde1t(dm, dm), ted1t(dm, dm)
real(rdt) vtp1(dm), vtp2(dm),TP
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> main body:
!CAUTION
	IF(.NOT.PRESENT(CHO)) THEN
		TP=THIS%BTAT
		THIS%BTAT=0.0
	END IF

    CALL GETTDE(TDE,TDE1T,THIS%BTAT,THIS%SPH,THIS%SPH1T,THIS%SV1X,THIS%SW1X,THIS%SV1X1T,THIS%SW1X1T)
	IF(.NOT.PRESENT(CHO)) THEN
		THIS%BTAT=TP
	END IF

    ted=TRANSPOSE(TDE)
    ted1t=TRANSPOSE(TDE1T)
      
    rea=THIS%hee
    rea(1)=rea(1)+THIS%XX+THIS%su
    rea(2)=rea(2)+THIS%sv
    rea(3)=rea(3)+THIS%sw
    call abplsv(rc, dm, dm, npt, rea, ted, cdlct) 
	
	
    veal(1)=THIS%su1t
    veal(2)=THIS%sv1t
    veal(3)=THIS%sw1t
    call abplsv(vc, dm, dm, npt, veal, ted1t, cdlct) 
	
    do 5 i=1, npt 
		!rc(:, i)=rea
		!vc(:, i)=veal
        vtp1=rc(:, i)
        CALL VCP(vtp2, THIS%omge, vtp1) 
        vc(:, i)=vc(:, i)+vtp2 
5    continue

end subroutine rvclct
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> the purpose:
subroutine rvclct2(this,rea, ted, dm, cho) 
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> modules used:
implicit none
class(element) :: this
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> dummy arguments / interface: 
!-> dm == 3.
!-> uvc0 ==6.
integer, intent(in):: dm
real(rdt), intent(out):: rea(dm),  ted(dm, dm)
integer,optional :: cho
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> FUNCTIONS INVOKED:
!->
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> SUBROUTINES INVOKED:
!->       GETTDE, abplsv, VCP     
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> LOCAL VARIABLES:

real(rdt) tde(dm, dm), tde1t(dm, dm), ted1t(dm, dm)
real(rdt) vtp1(dm), vtp2(dm),TP
!->+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!-> main body:
!CAUTION
	IF(.NOT.PRESENT(CHO)) THEN
		TP=THIS%BTAT
		THIS%BTAT=0.0
	END IF

    CALL GETTDE(TDE,TDE1T,THIS%BTAT,THIS%SPH,THIS%SPH1T,THIS%SV1X,THIS%SW1X,THIS%SV1X1T,THIS%SW1X1T)
	IF(.NOT.PRESENT(CHO)) THEN
		THIS%BTAT=TP
	END IF

    ted=TRANSPOSE(TDE)!数组转置
      
    !刚体位移
    rea(1)=THIS%su
    rea(2)=THIS%sv
    rea(3)=THIS%sw


end subroutine rvclct2
!->+++++++++++++++++++++++++++++++++++++++++++++
!计算力矩载荷
SUBROUTINE UMINT(THIS,MTT)
IMPLICIT NONE
CLASS(ELEMENT) :: THIS
REAL(RDT),INTENT(OUT)::MTT(3)

REAL(RDT) :: TX12,SXBP,MYBP,MZBP

    TX12=THIS%SU1X+0.5*THIS%SV2X**2+0.5*THIS%SW2X**2

    SXBP=THIS%EAB0T*TX12-THIS%SV2X*THIS%EAB1B-THIS%SW2X*THIS%EAB2B&
            +THIS%GJT*THIS%SPH1X+THIS%EAB3T*THIS%SALP1X+(THIS%TA0T*THIS%EAB3PT+THIS%EAB14T)*THIS%SALP&
            +THIS%EAB1T*THIS%SGE1X+THIS%EAB2T*THIS%SGZ1X+(THIS%EAB12T+THIS%TA0T*THIS%EAB2T)*THIS%SGE+(THIS%EAB10T-THIS%TA0T*THIS%EAB1T)*THIS%SGZ

    MYBP=THIS%EAZAT*TX12-THIS%SV2X*THIS%EIEZB-THIS%SW2X*THIS%EIEEB&
            +THIS%EAB2T*THIS%SPH1X+THIS%EAD2T*THIS%SALP1X+(THIS%TA0T*THIS%EAD2PT+THIS%EAB7T)*THIS%SALP&
            +THIS%EIEZT*THIS%SGE1X+THIS%EIEET*THIS%SGZ1X+(THIS%GEAZBT+THIS%TA0T*THIS%EIEET)*THIS%SGE+(THIS%GZAZCT-THIS%TA0T*THIS%EIEZT)*THIS%SGZ

    MZBP=THIS%EAEAT*TX12-THIS%SV2X*THIS%EIZZB-THIS%SW2X*THIS%EIZEB&
            +THIS%EAB1T*THIS%SPH1X+THIS%EAD1T*THIS%SALP1X+(THIS%TA0T*THIS%EAD1PT+THIS%EAB6T)*THIS%SALP&
            +THIS%EIZZT*THIS%SGE1X+THIS%EIEZT*THIS%SGZ1X+(THIS%GEAEBT+THIS%TA0T*THIS%EIEZT)*THIS%SGE+(THIS%GZAECT-THIS%TA0T*THIS%EIZZT)*THIS%SGZ
    MZBP=-MZBP
    
    MTT=(/-MYBP, MZBP, SXBP/)  
    
END SUBROUTINE UMINT
!->+++++++++++++++++++++++++++++++++++++++++++++
END MODULE
