MODULE INPUT_CLASS
USE INPUTS_CLASS
TYPE,PUBLIC :: INPUT

    TYPE(IPTIN) :: IPT
    TYPE(egnin) :: egn
    TYPE(fwdin) :: fwd
    TYPE(secin) :: sec
    TYPE(trmin) :: trm
    TYPE(ifwin) :: ifw
    TYPE(vtxin) :: vtx
    TYPE(cfdin) :: cfd
    TYPE(matin) :: mat

    TYPE(DFMin) :: DFX
    
CONTAINS

    PROCEDURE,PUBLIC :: INITIAL1
    PROCEDURE,PUBLIC :: INITIAL2
    PROCEDURE,PUBLIC :: NODIM
    PROCEDURE,PUBLIC :: GETMASS

END TYPE INPUT
!->+++++++++++++++++++++++++++++++++++++++++++++
CONTAINS
SUBROUTINE INITIAL1(THIS,IIN1)
IMPLICIT NONE
CLASS(INPUT) :: THIS
INTEGER,INTENT(IN) :: IIN1

    CALL THIS%IPT%READIPT(IIN1)

    CALL THIS%EGN%READEGN(IIN1)


!    if(THIS%IPT%SOL.EQ.2) then
        CALL THIS%FWD%READFWD(IIN1)
!    END IF

!    if(THIS%IPT%SOL.NE.0) then
        CALL THIS%IFW%READIFW(IIN1)
!    END IF
        CALL THIS%SEC%READSEC(IIN1)
		
    if(THIS%IPT%mktrim.ne.-1) then
        CALL THIS%trm%READTRM(IIN1)
    END IF

    if(THIS%IPT%MKIM.EQ.3.or.THIS%IPT%MKIM.EQ.4) then
        CALL THIS%VTX%READVTX(IIN1)
    END IF

    !if(THIS%IPT%MKFM.EQ.4) then
        CALL THIS%DFX%READDFM(IIN1)
        !CALL THIS%CFD%READCFD(IIN1)
    !END IF

END SUBROUTINE

SUBROUTINE INITIAL2(THIS,IIN2)
IMPLICIT NONE
CLASS(INPUT) :: THIS
INTEGER,INTENT(IN) :: IIN2

	CALL THIS%MAT%READMAT(IIN2)

END SUBROUTINE

REAL(RDT) FUNCTION GETMASS(THIS)
IMPLICIT NONE
CLASS(INPUT) :: THIS

GETMASS=3.0*THIS%IPT%RHA*THIS%IPT%alcsrf*&
                THIS%IPT%cchordrf*THIS%MAT%r/&
                THIS%IPT%lockn
END FUNCTION

SUBROUTINE NODIM(THIS)
IMPLICIT NONE
CLASS(INPUT) :: THIS

REAL(RDT) :: R,OMG,MASS_O,MASS
INTEGER :: I

    R=THIS%MAT%R
    OMG=THIS%MAT%OMG
    MASS_O=THIS%GETMASS()
    THIS%MAT%R=THIS%MAT%R/R
    THIS%MAT%OMG=THIS%MAT%OMG/OMG
    THIS%IPT%cchordrf=THIS%IPT%cchordrf/R

    MASS=MASS_O/THIS%GETMASS()


	DO I=1,THIS%MAT%NBPL
		THIS%MAT%MASS(1:3,1:3,I)=THIS%MAT%MASS(1:3,1:3,I)/MASS
		THIS%MAT%MASS(1:3,4:6,I)=THIS%MAT%MASS(1:3,4:6,I)/MASS/R
		THIS%MAT%MASS(4:6,1:3,I)=THIS%MAT%MASS(4:6,1:3,I)/MASS/R
		THIS%MAT%MASS(4:6,4:6,I)=THIS%MAT%MASS(4:6,4:6,I)/R**2

		IF(THIS%MAT%CHO.EQ.0) THEN
		  THIS%MAT%STIFF(1:1,1:1,I)=THIS%MAT%STIFF(1:1,1:1,I)/MASS/OMG**2/R**2
		  THIS%MAT%STIFF(1:1,2:4,I)=THIS%MAT%STIFF(1:1,2:4,I)/MASS/OMG**2/R**3
		  THIS%MAT%STIFF(2:4,1:1,I)=THIS%MAT%STIFF(2:4,1:1,I)/MASS/OMG**2/R**3
		  THIS%MAT%STIFF(2:4,2:4,I)=THIS%MAT%STIFF(2:4,2:4,I)/MASS/OMG**2/R**4
		ELSE IF(THIS%MAT%CHO.EQ.1)  THEN
		  THIS%MAT%STIFF(1:3,1:3,I)=THIS%MAT%STIFF(1:3,1:3,I)/MASS/OMG**2/R**2
		  THIS%MAT%STIFF(1:3,4:6,I)=THIS%MAT%STIFF(1:3,4:6,I)/MASS/OMG**2/R**3
		  THIS%MAT%STIFF(4:6,1:3,I)=THIS%MAT%STIFF(4:6,1:3,I)/MASS/OMG**2/R**3
		  THIS%MAT%STIFF(4:6,4:6,I)=THIS%MAT%STIFF(4:6,4:6,I)/MASS/OMG**2/R**4
		END IF
	END DO
	
END SUBROUTINE
END MODULE
