MODULE INPUTPROS_CLASS
USE INPUTPRO_CLASS
IMPLICIT NONE
!->+++++++++++++++++++++++++++++++++++++++++++++
TYPE,PUBLIC :: INPUTPROS
    
    INTEGER :: N_MAT
    TYPE(INPUTPRO),ALLOCATABLE :: MATER(:)

CONTAINS
    PROCEDURE,PUBLIC :: INITIAL

END TYPE INPUTPROS
!->+++++++++++++++++++++++++++++++++++++++++++++
CONTAINS
!->+++++++++++++++++++++++++++++++++++++++++++++
!->+++++++++++++++++++++++++++++++++++++++++++++
!->+++++++++++++++PUBLIC++++++++++++++++++++++++++
!->+++++++++++++++++++++++++++++++++++++++++++++
SUBROUTINE INITIAL(THIS,IIN,IOUT,INPU)
USE INPUT_CLASS
IMPLICIT NONE
CLASS(INPUTPROS) :: THIS
INTEGER,INTENT(IN) :: IIN,IOUT
CLASS(INPUT) :: INPU
INTEGER :: I

	THIS%N_MAT=INPU%IPT%NBPL
	ALLOCATE(THIS%MATER(THIS%N_MAT))
	
	WRITE(IOUT,*) THIS%N_MAT
	WRITE(IOUT,*) 
	IF(INPU%MOD%CHO.EQ.5) THEN
		DO I=1,THIS%N_MAT
			WRITE(IOUT,*) 
			WRITE(IOUT,*) I
			CALL THIS%MATER(I)%INITIAL_MAT(IIN,IOUT,INPU)
		END DO
	ELSE
		DO I=1,THIS%N_MAT
			WRITE(IOUT,*) 
			WRITE(IOUT,*) I
			THIS%MATER(I)%RL=REAL(I-1.0)*(INPU%IPT%R-INPU%IPT%EL1)/(INPU%IPT%NBPL-1)+INPU%IPT%EL1
            THIS%MATER(I)%RL=THIS%MATER(I)%RL/INPU%IPT%R
			THIS%MATER(I)%BTA=INPU%MOD%TAO*(THIS%MATER(I)%RL-0.75)
			THIS%MATER(I)%TAO=INPU%MOD%TAO
			CALL THIS%MATER(I)%INITIAL_MAT(IIN,IOUT,INPU)	
		END DO
	END IF
	INPU%MOD%CHO=THIS%MATER(1)%CHO
	
END SUBROUTINE
END MODULE
