MODULE MBEAMAERO
USE GlobalDataFun
IMPLICIT NONE

    REAL(RDT),ALLOCATABLE :: RLUDAUD(:)
    REAL(RDT),ALLOCATABLE :: FLCST_ST(:,:),MLCST_ST(:,:)
    REAL(RDT),ALLOCATABLE :: FLCST_FR(:,:),MLCST_FR(:,:)

    INTEGER :: NPTS

    REAL(RDT),ALLOCATABLE :: rlud(:)
    INTEGER :: NNOD

END MODULE
